### Converting strings to dates

In [1]:
import numpy as np
import pandas as pd

In [7]:
date_strings = np.array(
    [
        "03-04-2005 11:35 PM", 
        "23-05-2010 12:01 AM", 
        "04-09-2009 09:09 PM",
        "04-09-2009 09:09 APM"]
)

[pd.to_datetime(date, format='%d-%m-%Y %I:%M %p', errors='coerce') for date in date_strings]

[Timestamp('2005-04-03 23:35:00'),
 Timestamp('2010-05-23 00:01:00'),
 Timestamp('2009-09-04 21:09:00'),
 NaT]

### Working with time zones

In [8]:
pd.Timestamp('2017-05-01 06:00:00', tz='Europe/London')

Timestamp('2017-05-01 06:00:00+0100', tz='Europe/London')

In [11]:
date = pd.Timestamp("2017-05-01 06:00:00")
date_in_london = date.tz_localize("Europe/London")
date_in_london

Timestamp('2017-05-01 06:00:00+0100', tz='Europe/London')

In [12]:
date_in_london.tz_convert("Africa/Abidjan")

Timestamp('2017-05-01 05:00:00+0000', tz='Africa/Abidjan')

In [15]:
from pytz import all_timezones
all_timezones[0:2]

['Africa/Abidjan', 'Africa/Accra']

### Select date and time

In [25]:
dataframe = pd.DataFrame()
dataframe['date'] = pd.date_range('1/1/2001', periods=100000, freq='h')
filtered_dataframe = dataframe[
    dataframe["date"].between("2002-01-01 01:00:00", "2002-01-01 04:00:00", inclusive="right")
]
filtered_dataframe

                    date
8762 2002-01-01 02:00:00
8763 2002-01-01 03:00:00
8764 2002-01-01 04:00:00

In [27]:
dataframe = dataframe.set_index(dataframe['date'])
dataframe.loc['2002-1-1 01:00:00':'2002-1-1 04:00:00']

                                   date
date
2002-01-01 01:00:00 2002-01-01 01:00:00
2002-01-01 02:00:00 2002-01-01 02:00:00
2002-01-01 03:00:00 2002-01-01 03:00:00
2002-01-01 04:00:00 2002-01-01 04:00:00

### Decomposition of temporal data into individual features

In [32]:
dataframe = pd.DataFrame()
dataframe['date'] = pd.date_range('1/1/2001', periods=150, freq='W')

dataframe['year'] = dataframe['date'].dt.year
dataframe['month'] = dataframe['date'].dt.month
dataframe['day'] = dataframe['date'].dt.day
dataframe['hour'] = dataframe['date'].dt.hour
dataframe['minute'] = dataframe['date'].dt.minute

dataframe.head(10)

        date  year  month  day  hour  minute
0 2001-01-07  2001      1    7     0       0
1 2001-01-14  2001      1   14     0       0
2 2001-01-21  2001      1   21     0       0
3 2001-01-28  2001      1   28     0       0
4 2001-02-04  2001      2    4     0       0
5 2001-02-11  2001      2   11     0       0
6 2001-02-18  2001      2   18     0       0
7 2001-02-25  2001      2   25     0       0
8 2001-03-04  2001      3    4     0       0
9 2001-03-11  2001      3   11     0       0

### Using the sliding window method

In [41]:
time_index = pd.date_range("01/01/2010", periods=5, freq="ME")
dataframe = pd.DataFrame(index=time_index)
dataframe["Stock_Pri.ce"] = [1, 2, 3, 4, 5]
dataframe.rolling(window=2).mean()

            Stock_Pri.ce
2010-01-31           NaN
2010-02-28           1.5
2010-03-31           2.5
2010-04-30           3.5
2010-05-31           4.5