In [22]:
import numpy as np
from sklearn.preprocessing import LabelBinarizer, MultiLabelBinarizer
import pandas as pd

### Transformation of features with nominal categories

In [23]:
feature = np.array([["Texas"], ["California"], ["Texas"], ["Delaware"], ["Texas"]])
one_hot = LabelBinarizer()
one_hot.fit_transform(feature)
one_hot.classes_

array(['California', 'Delaware', 'Texas'], dtype='<U10')

#### Reverse transform

In [24]:
one_hot.inverse_transform(one_hot.transform(feature))

array(['Texas', 'California', 'Texas', 'Delaware', 'Texas'], dtype='<U10')

In [25]:
pd.get_dummies(feature[:, 0])

   California  Delaware  Texas
0       False     False   True
1        True     False  False
2       False     False   True
3       False      True  False
4       False     False   True

In [26]:
multiclass_feature = [
    ("Texas", "Florida"),
    ("California", "Alabama"),
    ("Texas", "Florida"),
    ("Delaware", "Florida"),
    ("Texas", "Alabama")]

one_hot_multiclass = MultiLabelBinarizer()
one_hot_multiclass.fit_transform(multiclass_feature)

array([[0, 0, 0, 1, 1],
       [1, 1, 0, 0, 0],
       [0, 0, 0, 1, 1],
       [0, 0, 1, 1, 0],
       [1, 0, 0, 0, 1]])

In [27]:
one_hot_multiclass.classes_

array(['Alabama', 'California', 'Delaware', 'Florida', 'Texas'],
      dtype=object)

### Transformation of features with ordinal categories

In [29]:
dataframe = pd.DataFrame({"Score": ["Low", "Low", "Medium", "Medium", "High"]})
scale_mapper = {
    "Low": 1,
    "Medium": 2,
    "High": 3}
dataframe["Score"] = dataframe["Score"].replace(scale_mapper)
dataframe.head()

  Score
0     1
1     1
2     2
3     2
4     3

In [32]:
dataframe = pd.DataFrame({
    "Score": ["Low", "Low", "Medium", "Medium", "High","Barely More Than Medium"]})
scale_mapper = {
    "Low": 1,
    "Medium": 2,
    "Barely More Than Medium": 3,
    "High": 4}
dataframe["Score"] =dataframe["Score"].replace(scale_mapper)
dataframe.head(6)

  Score
0     1
1     1
2     2
3     2
4     4
5     3

### Transformation of feature dictionaries

In [34]:
from sklearn.feature_extraction import DictVectorizer

data_dict = [
    {"Red": 2, "Blue": 4},
    {"Red": 4, "Blue": 3},
    {"Red": 1, "Yellow": 2},
    {"Red": 2, "Yellow": 2},
]

dict_vectorizer = DictVectorizer(sparse=False)
data_vectorized = dict_vectorizer.fit_transform(data_dict)
print(data_vectorized)

[[4. 2. 0.]
 [3. 4. 0.]
 [0. 1. 2.]
 [0. 2. 2.]]